# Example: https://b-nova.com/en/home/content/strengthen-your-system-with-tetragons-ebpf-based-security-observability-and-runtime-enforcement-capabilities
# https://grsecurity.net/tetragone_a_lesson_in_security_fundamentals

apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "exec policy"
spec:
  kprobes:
  # int execve(const char *pathname, char *const argv[],char *const envp[]);
  - call: "__x64_sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchPIDs:
      - operator: NotIn
        followForks: false
        isNamespacePID: true
        values:
        - 0
        #- 1
      
      matchArgs:
      - index: 0
        operator: "Prefix"
        values:
        - /usr/bin

