--- 
services: 
  tracee-agent: 
    image: aquasec/tracee:0.16.0
    container_name: tracee-agent 
    hostname:       tracee-agent 
    pid: host 
    privileged: true 
    environment: 
      - LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host 
    volumes: 
      - type:   bind 
        source: /etc/os-release 
        target: /etc/os-release-host 
        read_only: true

      - type:   bind 
        source: /boot
        target: /boot
        read_only: true

      - type:   bind 
        source: ./files
        target:  /tracee/configs
        read_only: true
    command: 
      - --config /tracee/configs/config.yml
      - --policy /tracee/configs/policy/exec.yml
      - --policy /tracee/configs/policy/open.yml
      - --policy /tracee/configs/policy/write.yml
#      - --policy /tracee/configs/policy/signature_events.yml
