---
services:
  tracee-agent:
    image: aquasec/tracee:0.11.0
    container_name: tracee-agent
    hostname:       tracee-agent
    pid:      host
    privileged: true
    environment:
      - LIBBPFGO_OSRELEASE_FILE=/etc/os-release-host
    volumes:
      - type:   bind
        source: /etc/os-release
        target: /etc/os-release-host
        read_only: true
      - type:   bind
        source: /boot
        target: /boot
        read_only: true
    command: 
      - trace

      - --trace 2:container
      - --trace 2:event=openat 
      - --trace 2:openat.args.pathname=/etc/passwd
      - --trace 2:openat.args.pathname='/tmp*'

      - --trace 3:container
      - --trace 3:comm=bash,sh
      - --trace 3:follow
      
      - --trace 4:container
      - --trace 4:comm=whoami,cat
      
      - --output table
