---
apiVersion: v1
kind: Namespace
metadata:
  name: infosec
  labels:
    pod-security.kubernetes.io/audit: baseline    
    pod-security.kubernetes.io/audit-version: v1.27

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracee-policies
  namespace: infosec
  labels:
    app.kubernetes.io/name: tracee
data:
  signatures.yaml: |-
    name: signature_events
    description: traces all signature events
    defaultActions:
      - log
    scope:
      - global
    rules:
      - event: stdio_over_socket
      - event: k8s_api_connection
      - event: aslr_inspection
      - event: proc_mem_code_injection
      - event: docker_abuse
      - event: scheduled_task_mod
      - event: ld_preload
      - event: cgroup_notify_on_release
      - event: default_loader_mod
      - event: sudoers_modification
      - event: sched_debug_recon
      - event: system_request_key_mod
      - event: cgroup_release_agent
      - event: rcd_modification
      - event: core_pattern_modification
      - event: proc_kcore_read
      - event: proc_mem_access
      - event: hidden_file_created
      - event: anti_debugging
      - event: ptrace_code_injection
      - event: process_vm_write_inject
      - event: disk_mount
      - event: dynamic_code_loading
      - event: fileless_execution
      - event: illegitimate_shell
      - event: kernel_module_loading
      - event: k8s_cert_theft
      - event: proc_fops_hooking
      - event: syscall_hooking
      - event: dropped_executable
  shell.yml: |-
    name: shell
    description: shell
    scope:
      - container
      - "!container"
      - comm=sh,bash
      - follow
    defaultActions: 
      - log
    rules:
      - event: sched_process_exec
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracee-config
  namespace: infosec
  labels:
    app.kubernetes.io/name: tracee
data:
  config.yaml: |-
    cache:
      - cache-type=mem
      - mem-cache-size=512
    perf-buffer-size: 1024
    containers: true
    healthz: true
    metrics: true
    pprof: false
    pyroscope: false
    listen-addr: :3366
    log:
        - info
    output:
        - json
        - option:parse-arguments
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tracee
  namespace: infosec
  labels:
    app.kubernetes.io/name: tracee
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tracee
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tracee
      name: tracee
    spec:
      containers:
      - name: tracee
        image: docker.io/aquasec/tracee:0.16.0
        imagePullPolicy: IfNotPresent
        command: 
          - /tracee/tracee
        args:
          - --policy
          - /tracee/policies
          - --config 
          - /tracee/config.yaml
        env:
          - name: LIBBPFGO_OSRELEASE_FILE
            value: /etc/os-release-host
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3366
        securityContext:
          privileged: true
        
        volumeMounts:
        - name: boot-tracee
          mountPath: /boot
          readOnly: true
        
        - name: etc-os-release
          mountPath: /etc/os-release-host
          readOnly: true
        
        - name: containerd-sock
          mountPath: /var/run/containerd/containerd.sock
          readOnly: true
        
        - name: tracee-config
          mountPath: /tracee/config.yaml
          subPath: config.yaml
          readOnly: true
        
        - name: tracee-policies
          mountPath: /tracee/policies
          readOnly: true

      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      
      volumes:
      - name: boot-tracee
        hostPath:
          path: /boot
        
      - name: etc-os-release
        hostPath:
          path: /etc/os-release
        
      - name: containerd-sock
        hostPath:
          path: /var/run/containerd/containerd.sock

      - name: tracee-config
        configMap:
          name: tracee-config

      - name: tracee-policies
        configMap:
          name: tracee-policies