---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: infosec
  labels:
    app.kubernetes.io/name: filebeat

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    app.kubernetes.io/name: filebeat
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: filebeat
  namespace: infosec
  labels:
    app.kubernetes.io/name: filebeat
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: infosec
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat
  namespace: infosec
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: infosec
roleRef:
  kind: Role
  name: filebeat
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: infosec
  labels:
    app.kubernetes.io/name: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
      - type: kubernetes
        include_labels:
        add_resource_metadata:
        node: ${NODE_NAME}
        templates:
        - condition:
            equals:
              kubernetes.labels.app.kubernetes.io/name: tracee   
          config:
          - type: container
            paths:
              - /var/log/containers/*-${data.kubernetes.container.id}.log
            fields_under_root: true
            close_renamed: true
            clean_removed: true
            json.keys_under_root: true

    processors:
      - add_host_metadata:

    tags: ['filebeat-tracee'] 

    setup.kibana:
      enable: false

    output.elasticsearch:
      enabled: false

    output.logstash:
      enabled: false

    output.console:
      enabled: true
      pretty:  true

    processors: 
      - add_host_metadata: ~

    monitoring.enabled: false
    
    logging.to_stderr: true
    logging.level: info 
    logging.metrics.enabled: true
    logging.json: false

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: infosec
  labels:
    app.kubernetes.io/name: filebeat
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: filebeat
  template:
    metadata:
      labels:
        app.kubernetes.io/name: filebeat
      name: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: filebeat
        image: elastic/filebeat:8.8.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
          "--strict.perms=false"
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        
        volumeMounts:
        - name: filebeat-config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
          readOnly: true
        - name: filebeat-state
          mountPath: /usr/share/filebeat/data
          readOnly: false
        - name: filebeat-container-logs
          mountPath: /var/log/containers
          readOnly: true
        - name: filebeat-pod-logs
          mountPath: /var/log/pods
          readOnly: true
      
      volumes:
      - name: filebeat-config
        configMap:
          name: filebeat-config
          defaultMode: 0644
      - name: filebeat-state
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
      - name: filebeat-container-logs
        hostPath:
          path: /var/log/containers
      - name: filebeat-pod-logs
        hostPath:
          path: /var/log/pods

      
