---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-name
  labels:
    app: nginx-app
spec:
  replicas: 2
  #strategy: Recreate
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
        - name: nginx-pod
          image: nginx:1.14.1
          ports:
          - containerPort: 80
