---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-name
  labels:
    app: nginx-app
  annotations:
    container.apparmor.security.beta.kubernetes.io/nginx-pod: runtime/default
spec:
  containers:
  - name: nginx-pod
    image: nginx:1.14.1
    ports:
    - containerPort: 80