---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: dev-admin
subjects:
- kind: ServiceAccount
  name: dev-admin
roleRef:
  kind: Role
  name: dev-admin
  apiGroup: rbac.authorization.k8s.io
