---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-admin
subjects:
- kind: ServiceAccount
  name: dev-admin
  namespace: dev
roleRef:
  kind: ClusterRole
  name: cluster-admin